apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: lidar-ui
build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/lidar-ui
deploy:
  kubectl:
    manifests:
    - k8s/lidar-ui-deployment.yaml
    - k8s/lidar-ui-service.yaml
    - k8s/lidar-ui-ingress.yaml
