apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: lidar-ui

build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/lidar-ui
    jib:
      project: server
  tagPolicy:
    sha256: {}

deploy:
  helm:
    releases:
    - name:  lidar-ui
      chartPath: chart
      artifactOverrides:
        image: nexus-docker-public-hosted.ossim.io/lidar-ui
