apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  template:
    metadata:
      name:  {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name:  {{ .Chart.Name }}
          image: {{ .Values.global.image.name }}
          imagePullPolicy: IfNotPresent
          env:
            - name: LIDAR_INDEXER_URL
              value: https://lidar-indexer.ossim.io/lidarProducts/findAll
            - name: BANNER_CLASSIFICATION_TEXT
              value: green
            - name: BANNER_CLASSIFICATION_TEXT_COLOR
              value: white
            - name: BANNER_CLASSIFICATION_FONT_WEIGHT
              value: bold
      restartPolicy: Always
  selector:
    matchLabels:
      app:  {{ .Chart.Name }}
