apiVersion: v1
kind: Service
metadata:
  name:  {{ .Chart.Name }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app:  {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}