micronaut:
  application:
    name: server
---

settings:
  banner:
    text: ${BANNER_CLASSIFICATION_TEXT:Unclassified}
    background-color: ${BANNER_CLASSIFICATION_BACKGROUND_COLOR:green}
    text-color: ${BANNER_CLASSIFICATION_TEXT_COLOR:white}
    font-weight: ${BANNER_CLASSIFICATION_FONT_WEIGHT:bold}
  lidar-indexer:
    url: ${LIDAR_INDEXER_URL:`https://lidar-indexer.ossim.io/lidarProducts/findAll`}
  lidar-s3-web-host:
    url: ${LIDAR_S3_WEB_HOST_URL:`https://gsp-lidar-webhost.s3.amazonaws.com`}
  pagination:
    posts-per-page: 4

---
micronaut:
  server:
    cors:
      enabled: true

---
micronaut:
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

