micronaut:
  application:
    name: server
---

settings:
  banner:
    text: "Unclassified"
    background-color: rgb(200,0,255)
    text-color: white
    font-weight: bold
  lidar-indexer:
    url: http://lidar-indexer.ossim.io/lidarProducts/findAll

---
micronaut:
  server:
    cors:
      enabled: true

---
micronaut:
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

