apiVersion: v1
kind: Service
metadata:
  name: lidar-ui
spec:
  #clusterIP: 172.20.31.75
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: lidar-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}