apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidar-ui
  labels:
    app: lidar-ui
spec:
  replicas: 1
  template:
    metadata:
      name: lidar-ui
      labels:
        app: lidar-ui
    spec:
      containers:
        - name: lidar-ui
          image: nexus-docker-public-hosted.ossim.io/lidar-ui
          imagePullPolicy: IfNotPresent
          env:
            - name: LIDAR_INDEXER_URL
              value: https://lidar-indexer.ossim.io/lidarProducts/findAll
            - name: BANNER_CLASSIFICATION_TEXT
              value: green
            - name: BANNER_CLASSIFICATION_TEXT_COLOR
              value: white
            - name: BANNER_CLASSIFICATION_FONT_WEIGHT
              value: bold
      restartPolicy: Always
  selector:
    matchLabels:
      app: lidar-ui
